

temporal_difference_learning:
	python3 -m temporal-difference-learning.q_learning
	python3 -m temporal-difference-learning.sarsa
	python3 -m temporal-difference-learning.double_q_learning
	python3 -m temporal-difference-learning.tabluar_td_0
	python3 -m temporal-difference-learning.expected_sarsa	
